### ISSUE TITLE
cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by wenxingxingxing** [Outsider565/LoRA-GA#16]
您好，我在使用example/float_llama2-7b_metamath.py进行复现时遇到这份报错：
Traceback (most recent call last):
  File "/home/LoRA-GA/examples/float_llama2-7b_metamath.py", line 142, in <module>
    Fire(main)
  File "/home/anaconda3/envs/loraga/lib/python3.10/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/anaconda3/envs/loraga/lib/python3.10/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/anaconda3/envs/loraga/lib/python3.10/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/LoRA-GA/examples/float_llama2-7b_metamath.py", line 102, in main
    model = train_text_to_text_model(
  File "/home/LoRA-GA/examples/utils.py", line 283, in train_text_to_text_model
    trainer = TrainerClass(
  File "/home/LoRA-GA/examples/logTrainer.py", line 57, in __init__
    super().__init__(
  File "/home/anaconda3/envs/loraga/lib/python3.10/site-packages/transformers/utils/deprecation.py", line 165, in wrapped_func
    return func(*args, **kwargs)
  File "/home/anaconda3/envs/loraga/lib/python3.10/site-packages/transformers/trainer.py", line 600, in __init__
    self.optimizer, self.lr_scheduler = optimizers
TypeError: cannot unpack non-iterable NoneType object

硬件环境：
system: ubuntu

GPU: 4*A800

请问有没有遇到过这个bug

**Comment by KrisLuo-cyber** [comment]
请问，这是如何解决的呢？

**Comment by boxiaowave** [comment]
> 请问，这是如何解决的呢？

transformers 版本问题，4.44.0应该可以

**Comment by wenxingxingxing** [comment]
> 请问，这是如何解决的呢？

将transformers 换成4.44.0版本
